version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: springblog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: springblogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: springblog-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springblogdb
      SPRING_DATASOURCE_USERNAME: bloguser
      SPRING_DATASOURCE_PASSWORD: blogpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: springblog-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  mysql_data:
