spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springblogdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bloguser
    password: blogpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret-key: 6b4c3b3d8f05c622d0cb9e019cb24b725107b907127a53363a3fe5a511650844
    expiration-time: 3600000

##prod
#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/springblogdb
#    username: bloguser
#    password: blogpass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8080
